routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });



// Route::group(['namespace'=>'App\Http\Controllers', 'prefix' => 'admin'], function ()
// {
//     Route::get('/', [
//         'uses'=>'AdminController@index',
//         'as'=>'admin_index'
//     ]);

//     Route::get('/add', [
//         'uses'=>'AdminController@add',
//         'as'=>'admin_add'
//     ]);

//     Route::get('/edit', [
//         'uses'=>'AdminController@edit',
//         'as'=>'admin_edit'
//     ]);

//     Route::get('/delete', [
//         'uses'=>'AdminController@delete',
//         'as'=>'admin_delete'
//     ]);
    
    
//     Route::post('/', [
//         'uses'=>'AdminController@index',
//         'as'=>'admin_index'
//         ]);
    
// });


Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home_page');
Route::get('produkt/'.'{id}', 'App\Http\Controllers\HomeController@product')->name('show_product');

Route::get('/contact', 'App\Http\Controllers\ContactUsFormController@createForm')->name('contact_form');

Route::post('/contact', 'App\Http\Controllers\ContactUsFormController@ContactUsForm')->name('contact.store');

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('routes', function() {
    \Artisan::call('route:list');
    return '<pre>' . \Artisan::output() . '</pre>';
    });

Route::group([['middleware' => 'auth'], 'prefix'=>'admin_panel','as'=>'admin_panel.'], function(){
    Route::get('/', 'App\Http\Controllers\AdminController@index')->name('panel_admina');
    Route::post('/checklogin', 'App\Http\Controllers\AdminController@checklogin');
    Route::get('/panel', [
                'uses'=>'App\Http\Controllers\AdminController@panel'
                
            ])->name('admin_index');
    
    Route::get('/logout', 'App\Http\Controllers\AdminController@logout');


    Route::get('/add_form', 'App\Http\Controllers\AdminController@add_form')->name('add_form');
    Route::post('/add', 'App\Http\Controllers\AdminController@add')->name('add');

    Route::get('edit_form/'.'{id}', 'App\Http\Controllers\AdminController@edit_form')->name('edit_form');
    Route::post('edit', 'App\Http\Controllers\AdminController@edit')->name('edit');

    Route::get('delete/'.'{id}', 'App\Http\Controllers\AdminController@delete')->name('delete');
    });

resources/views/contact.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kontakt</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}?=<?php echo time(); ?>">
</head>

<body>
    
    @include('main_menu')

    <div class="container mt-5">

        <!-- Success message -->
        @if(Session::has('success'))
            <div class="alert alert-success">
                {{Session::get('success')}}
            </div>
        @endif

        <form action="" method="post" action="{{ route('contact.store') }}">

    @csrf

    <div class="form-group">
        <label>Name</label>
        <input type="text" class="form-control {{ $errors->has('name') ? 'error' : '' }}" name="name" id="name">

        <!-- Error -->
        @if ($errors->has('name'))
        <div class="error">
            {{ $errors->first('name') }}
        </div>
        @endif
    </div>

    <div class="form-group">
        <label>Email</label>
        <input type="email" class="form-control {{ $errors->has('email') ? 'error' : '' }}" name="email" id="email">

        @if ($errors->has('email'))
        <div class="error">
            {{ $errors->first('email') }}
        </div>
        @endif
    </div>

    <div class="form-group">
        <label>Phone</label>
        <input type="text" class="form-control {{ $errors->has('phone') ? 'error' : '' }}" name="phone" id="phone">

        @if ($errors->has('phone'))
        <div class="error">
            {{ $errors->first('phone') }}
        </div>
        @endif
    </div>

    <div class="form-group">
        <label>Subject</label>
        <input type="text" class="form-control {{ $errors->has('subject') ? 'error' : '' }}" name="subject"
            id="subject">

        @if ($errors->has('subject'))
        <div class="error">
            {{ $errors->first('subject') }}
        </div>
        @endif
    </div>

    <div class="form-group">
        <label>Message</label>
        <textarea class="form-control {{ $errors->has('message') ? 'error' : '' }}" name="message" id="message"
            rows="4"></textarea>

        @if ($errors->has('message'))
        <div class="error">
            {{ $errors->first('message') }}
        </div>
        @endif
    </div>

    <input type="submit" name="send" value="Submit" class="btn btn-dark btn-block">
</form>
    </div>
</body>

</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mail.blade.php
<h2>Hello</h2> <br><br>

You have got an email from : {{ $name }} <br><br>

User details: <br><br>

Name: {{ $name }} <br>
Email: {{ $email }} <br>
Phone: {{ $phone }} <br>
Subject: {{ $subject }} <br>
Message: {{ $user_query }} <br><br>

Thanks

resources/views/main_menu.blade.php
<div class="menu-container">
        <div class="menu-container-align">
            <ul class="main-menu">
                <li><a href="{{route('home_page')}}">Strona główna</a></li>
                <li><a href="{{route('contact_form')}}">Kontakt</a></li>
                <li><a target="blank" href="{{route('admin_panel.panel_admina')}}">Panel administratora</a></li>
            </ul>
        </div>
    </div>

resources/views/product_view.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{$product->name}}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}?=<?php echo time(); ?>">
</head>
<body>
@include('main_menu')

<div>


<?php
                $photo=explode('/',$product->photo);
                $path='public/storage/storage/';
                ?>
                <img class="rounded mx-auto d-block img-product" src="{{url('')}}<?php echo '/storage/storage/'.$photo[2] ?>" alt="photo">
                <h2 class="text-center">{{$product->name}}</h2>
                <p class="text-justify">{{$product->description}}</p>
</div>

</body>

</html>

resources/views/products.blade.php
<table class="table-products">
        <tr>
            <td class="td-id text-center">Id</td>
            <td class="td-product-name text-center">Nazwa produktu</td>
            <td class="td-description text-center">Opis</td>
            <td class="td-photo text-center">Zdjęcie</td>
            <td colspan="3" class="td-actions text-center">Akcje</td>
            
        </tr>

@foreach($products as $product)
    @if($product->id!='')
        <tr>
            <td>
                {{$product->id}}
            </td>
            <td>
                {{$product->name}}
            </td>
            <td>
                {{ \Illuminate\Support\Str::limit($product->description, 50, $end='...') }}
            </td>
            <td>
                <?php
                $photo=explode('/',$product->photo);
                $path='public/storage/storage/';
                ?>
                <img src="{{url('')}}<?php echo '/storage/storage/'.$photo[2] ?>" alt="photo" height="50px">
            </td>
            <td>
                <a class="show-btn" href="{{route('show_product', ['id'=>$product->id])}}">Podgląd</a>
            </td>
            <td>
                <a class="edit-btn" href="{{route('admin_panel.edit_form', ['id'=>$product->id])}}">Edytuj</a>
            </td>
            <td>
                <a class="delete-btn" href="{{route('admin_panel.delete', ['id'=>$product->id])}}">Usuń</a>
            </td>
        </tr>
        @else
        "Brak produktów"
        @endif
    @endforeach
    
    </table>

<div class="pagination-container">
    {{ $products->links() }}
    </div>

    

resources/views/show_products.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Produkty</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}?=<?php echo time(); ?>">
</head>

<body>
@include('main_menu')
<h1 class="text-center">Lista produktów</h1>
<div class="products-container">
<div class="products-container-list">
@foreach($products as $product)
<div class="product-box">


<?php
                $photo=explode('/',$product->photo);
                $path='public/storage/storage/';
                ?>
                <div class="product-box-left">
                <img class="rounded mx-auto d-block img-product" src="{{url('')}}<?php echo '/storage/storage/'.$photo[2] ?>" alt="photo">
                </div>
                <div class="product-box-right">
                <h2><a href="{{route('show_product', ['id'=>$product->id])}}">{{$product->name}}</a></h2>
                <p>{{Str::limit($product->description, 100)}}</p>
</div>
</div>
@endforeach
</div>
</div>

</body>

</html>