routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });



// Route::group(['namespace'=>'App\Http\Controllers', 'prefix' => 'admin'], function ()
// {
//     Route::get('/', [
//         'uses'=>'AdminController@index',
//         'as'=>'admin_index'
//     ]);

//     Route::get('/add', [
//         'uses'=>'AdminController@add',
//         'as'=>'admin_add'
//     ]);

//     Route::get('/edit', [
//         'uses'=>'AdminController@edit',
//         'as'=>'admin_edit'
//     ]);

//     Route::get('/delete', [
//         'uses'=>'AdminController@delete',
//         'as'=>'admin_delete'
//     ]);
    
    
//     Route::post('/', [
//         'uses'=>'AdminController@index',
//         'as'=>'admin_index'
//         ]);
    
// });


Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home_page');
Route::get('produkt/'.'{id}', 'App\Http\Controllers\HomeController@product')->name('show_product');

Route::get('/contact', 'App\Http\Controllers\ContactUsFormController@createForm')->name('contact_form');

Route::post('/contact', 'App\Http\Controllers\ContactUsFormController@ContactUsForm')->name('contact.store');

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('routes', function() {
    \Artisan::call('route:list');
    return '<pre>' . \Artisan::output() . '</pre>';
    });

Route::group([['middleware' => 'auth'], 'prefix'=>'admin_panel','as'=>'admin_panel.'], function(){
    Route::get('/', 'App\Http\Controllers\AdminController@index')->name('panel_admina');
    Route::post('/checklogin', 'App\Http\Controllers\AdminController@checklogin');
    Route::get('/panel', [
                'uses'=>'App\Http\Controllers\AdminController@panel'
                
            ])->name('admin_index');
    
    Route::get('/logout', 'App\Http\Controllers\AdminController@logout');


    Route::get('/add_form', 'App\Http\Controllers\AdminController@add_form')->name('add_form');
    Route::post('/add', 'App\Http\Controllers\AdminController@add')->name('add');

    Route::get('edit_form/'.'{id}', 'App\Http\Controllers\AdminController@edit_form')->name('edit_form');
    Route::post('edit', 'App\Http\Controllers\AdminController@edit')->name('edit');

    Route::get('delete/'.'{id}', 'App\Http\Controllers\AdminController@delete')->name('delete');
    });

resources/views/admin_panel/add.blade.php
@if(isset(Auth::user()->email))

@extends('admin_layout.layout')
@section('content')

<form method="post" action="{{route('admin_panel.add')}}" enctype="multipart/form-data">
<input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
Nazwa produktu:<br />
<input type="text" name="product_name" class="product_name"><br />
Opis<br />
<textarea name="description" class="description"></textarea><br />
Zdjęcie <br />
<input type="file" name="photo"><br /><br />
<input type="submit">
</form>


@endsection
@else
<script>window.location = "/admin_panel";</script>
   @endif

resources/views/admin_panel/delete.blade.php
delete

resources/views/admin_panel/edit.blade.php
@if(isset(Auth::user()->email))

@extends('admin_layout.layout')
@section('content')

<form action="{{route('admin_panel.edit')}}" method="post" enctype="multipart/form-data">
<input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
<input type="hidden" value="{{$product->id}}" name="id">
Nazwa produktu:<br />
<input type="text" name="product_name" class="product_name" value="{{$product->name}}"><br />
Opis<br />
<textarea name="description" class="description">{{$product->description}}</textarea><br />
Zdjęcie <br />
<?php
    $photo=explode('/',$product->photo);
?>
<img src="{{url('')}}<?php echo '/storage/storage/'.$photo[2] ?>" alt="photo" width="50px"><br />
<input type="file" name="photo" class="photo"><br /><br />
<input type="submit">
</form>
<a href="{{route('admin_panel.admin_index')}}">Anuluj</a>

@endsection
@else
<script>window.location = "/admin_panel";</script>
   @endif

resources/views/admin_panel/index.blade.php
@if(isset(Auth::user()->email))

@extends('admin_layout.layout')
@section('content')


<a class="add-btn" href="{{route('admin_panel.add_form')}}">Dodaj</a>

<div style="width:100%;display:flex; justify-content: flex-end;">
<form method="post">
<input type="hidden" name="_token" value="{{ csrf_token() }}">
<input type="text" id="search_field" name="search_field" class="search_field" placeholder="Szukaj">
</form>
</div>


<div class="products-container">

        
    @include('products')


</div>






<!-- <a href="{{ url('/admin_panel/logout') }}">Logout</a> -->

<script>
$(document).ready(function(){
$(".search_field").keyup(function(){
let a=$(this).val();
//alert(a);
var url = "{{ route('admin_panel.admin_index')}}";
var token = "{{ csrf_token()}}";
let productsContainer = document.querySelector('.products-container');
console.log(productsContainer);
$.ajax({
type: "GET",
url: url,
 data: {a:a,_token:token},
dataType: 'json',
success: function(data)
{
console.log(a);
productsContainer.innerHTML = data.products;
//console.log(data.products);
},
error:function(){
alert(a);
}
})
});
});
</script>




@endsection
@else
<script>window.location = "/admin_panel";</script>
   @endif

resources/views/admin_panel/login.blade.php
<!DOCTYPE html>
<html>
 <head>
  <title>Admin Panel</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style type="text/css">
   .box{
    width:600px;
    margin:0 auto;
    border:1px solid #ccc;
   }
  </style>
 </head>
 <body>
  <br />
  <div class="container box">
   <h3 align="center">Panel administratora</h3><br />

   @if(isset(Auth::user()->email))
    <script>window.location="/admin_panel/panel";</script>
   @endif

   @if ($message = Session::get('error'))
   <div class="alert alert-danger alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>{{ $message }}</strong>
   </div>
   @endif

   @if (count($errors) > 0)
    <div class="alert alert-danger">
     <ul>
     @foreach($errors->all() as $error)
      <li>{{ $error }}</li>
     @endforeach
     </ul>
    </div>
   @endif

   <form method="post" action="{{ url('/admin_panel/checklogin') }}">
    {{ csrf_field() }}
    <div class="form-group">
     <label>Enter Email</label>
     <input type="email" name="email" class="form-control" />
    </div>
    <div class="form-group">
     <label>Enter Password</label>
     <input type="password" name="password" class="form-control" />
    </div>
    <div class="form-group">
     <input type="submit" name="login" class="btn btn-primary" value="Login" />
    </div>
   </form>
  </div>
 </body>
</html>